### PR TITLE
Aimbot Update

### PR DESCRIPTION
**Pull request by Brodys**
I removed a few things but this is my version of this cheat.

### CODE REVIEW

**Comment by Ashesh3** [comment]
How much is this better than original aimbot?

Thanks!

**Comment by Invalidity** [comment]
Isn't it better to use looping instead of if statements?

**Comment by Ashesh3** [comment]
@Invalidity looping for what? The  if statement are inside a loop which runs aimbot and esp..i think it's fine.

Just need to know how much does this improve the aimbot...

**Comment by Ashesh3** [comment]
Let's try to once :)

**Pull request merged**
